## This the first learning video tutorial
--> (python playlist vid -01)

In [1]:
1+2

3

In [2]:
a=10

In [3]:
print(a+5)

15


In [4]:
import this

The Zen of Python, by Tim Peters

Beautiful is better than ugly.
Explicit is better than implicit.
Simple is better than complex.
Complex is better than complicated.
Flat is better than nested.
Sparse is better than dense.
Readability counts.
Special cases aren't special enough to break the rules.
Although practicality beats purity.
Errors should never pass silently.
Unless explicitly silenced.
In the face of ambiguity, refuse the temptation to guess.
There should be one-- and preferably only one --obvious way to do it.
Although that way may not be obvious at first unless you're Dutch.
Now is better than never.
Although never is often better than *right* now.
If the implementation is hard to explain, it's a bad idea.
If the implementation is easy to explain, it may be a good idea.
Namespaces are one honking great idea -- let's do more of those!


## python tutorial-02

In [8]:
print("hello world")
print("day 2 of learning utsav")

hello world
day 2 of learning utsav


In [21]:
# single line and multiline comments
'''
lets make this festive vacation 
fruitful
'''
print("hello")

hello


In [23]:
# varaible decaration 
a=10
type(a)

int

In [24]:
a

10

In [26]:
hi=10
b=60
c="atg"

In [27]:
type(c)

str

In [31]:
d1= 22

In [33]:
first_name="Ayush"
print(first_name)

Ayush


In [35]:
a=10
b=20
print(a-b)

-10


In [37]:
# typecast converting floating number into integer
a=25.364
type(a)

float

In [38]:
int(a)

25

In [39]:
a

25.364

In [40]:
b

20

In [41]:
float(b)

20.0

In [43]:
#boolean
a1=True
b1=False

In [44]:
type(a1)

bool

In [45]:
a1 and b1

False

In [46]:
a1|b1

True

In [48]:
#stings
name1="hancy"
print(name1)
print(type(name1))

hancy
<class 'str'>


In [49]:
name1+"guffadi"

'hancyguffadi'

In [50]:
name1+str(1)

'hancy1'

In [2]:
#complex numbers
j=1.0-2.3j
j

(1-2.3j)

In [3]:
print(j.real,j.imag)

1.0 -2.3


In [4]:
#Dynamic typing 
a =10
a='ayush'

In [6]:
print(type(a))

<class 'str'>


In [7]:
#strong typing
a="Hello"

In [8]:
a+ "1"

'Hello1'

In [10]:
#string formating
a =100 
print("the value is=",a)

the value is= 100


In [15]:
first_name="Ayush"
last_name="Tamang"
print("The first name is {0} and last name is {1}".format(first_name,last_name))

The first name is Ayush and last name is Tamang


In [16]:
print("The first name is {1} and last name is {0}".format(first_name,last_name))

The first name is Tamang and last name is Ayush


In [17]:
print("The first name is {a} and last name is {b}".format(a=first_name, b=last_name))

The first name is Ayush and last name is Tamang


In [1]:
# input type
a=input("enter the number A ")
b= input("enter the number B ")
print(int(a)+int(b))

enter the number A 45
enter the number B 54
99


# python tutorial- 03

In [8]:
# if else statement 
val=input("Enter the number")
value_float=float(val)
if(value_float%2 == 0):
    print("The number is even")
else:
    print("the number is odd")

Enter the number45
the number is odd


In [10]:
## Age form
##nested if else condition
age= float(input("Enter the age"))

if(age<18):
    print("Minor Age")
elif(age>18 and age<=35):
    print("Mid Age")
elif(age>45 and age<=50):
    print("senior Mid Age")
else:
    print("Senior Citizen")

Enter the age33
Mid Age


In [2]:
##nested if else
age= float(input("Enter the age "))

if(age<18):
    print("Minor Age")
    if(age<15):
        print("your are in School")
    else:
        print("you are in college")
elif(age>18 and age<=35):
    print("Mid Age")
elif(age>45 and age<=50):
    print("senior Mid Age")
else:
    print("Senior Citizen")

Enter the age 17
Minor Age
you are in college


In [5]:
##loops statement
#for loop, while loop
lst=[1,2,3,4,5,6,7]
for i in lst:
    print(i**2)

1
4
9
16
25
36
49


In [7]:
#find the sum of all the elements in the list
lst=[1,2,3,4,5,6,7]
sum1 = 0
for i in lst:
    sum1 = sum1 + i
print(sum1)

28


In [ ]:
lst=[1,2,3,4,5,6,7]
sum1 = 0
for i in lst:
    sum1 = sum1 + i
    print(sum1)

In [18]:
#find the sum of even and odd number
lst=[1,2,3,4,5,6,7]
even_sum=0 
odd_sum =0
for i in lst:
    if(i%2==0):
        even_sum= even_sum+i
    else:
        odd_sum= odd_sum+ i
print(even_sum)
print(odd_sum)
# or by using string formating
print("Even sum is {} and odd sum is {}".format(even_sum, odd_sum))

12
16
Even sum is 12 and odd sum is 16


In [20]:
##while condition 
i =0
even_sum =0
odd_sum=0
while(i<=10):
    if(i%2==0):
        even_sum= even_sum+i
    else:
        odd_sum= odd_sum+ i
    i = i+1
print(even_sum,odd_sum)

30 25


In [24]:
#break 
x = 1
while(x<7):
    print(x)
       
    x=x+1

1
2
3
4
5
6


In [25]:
x = 1
while(x<7):
    print(x)
    if(x==4):
        break
       
    x=x+1

1
2
3
4


In [28]:
x = 1
while(x<7):
    
    if(x==4):
        break
    print(x)
       
    x=x+1

1
2
3


In [2]:
# continue(skips the statement)
x=0
while(x<7):
    x=x+1
    if(x==4):
        continue
    print(x)
 

1
2
3
5
6
7


## python tutorial- 04

### python operators
- logical

- equality

- comparision

- Airthmetic


 ### 4.1.1 Logical Operators,
In python following keywords are used for boolean operations -

    Keywords	Meaning
    not	unary negation
    and	conditional AND
    or	conditional OR

In [11]:
type(False)

bool

In [4]:
bool(1)

True

In [5]:
a = True
b =False

In [6]:
True and False

False

In [7]:
True or False

True

In [8]:
not False

True

In [9]:
age = int(input("Enter the age"))
if(age>18 and age<=35):
    print("mid age")

Enter the age21
mid age


In [10]:
age = int(input("Enter the age"))
if(age>18 or age<=35):
    print("success")

Enter the age15
success


## Equality Operators
Following operations are present in python for equlity check operation-

| Operators | Meaning                                                                 |
|-----------|-------------------------------------------------------------------------|
| `is`      | `a is b` returns true if variable/identifiers `a` and `b` point to the same object  |
| `is not`  | `a is not b` returns true if variable/identifiers `a` and `b` point to different objects |
| `==`      | `a == b` returns true if variable/identifiers `a` and `b` have the same value   |
| `!=`      | `a != b` returns true if variable/identifiers `a` and `b` have different values |



In [12]:
a = "atg"
b = "atg"
a==b

True

In [13]:
a = "atg"
b = "atg1"
a==b

False

In [15]:
age=int(input("Enter the  age"))
if age ==18:
    print("you are teen")

Enter the  age18
you are teen


In [26]:
a = "atg"
b = "atg"
print(id(a))
print(id(b))

2598666911344
2598666911344


In [27]:
a is b 

True

In [28]:
a == b

True

In [30]:
lst1 =[1,2,3]
lst2 =[1,2,3]
print(id(lst1))
print(id(lst2))

2598667679232
2598667574144


In [31]:
lst1 == lst2

True

In [32]:
lst1 is lst2

False

In [33]:
lst1 is not lst2

True

## comparison operators
    Operation	 Meaning

    <	less than
    
    <=	less than or equal to
    
    >	greater than
    
    >=	greater than or equal to
    

In [2]:
marks= float(input("Enter the marks "))
if(marks>=35):
    print("Pass")
    if(marks>=50 and marks<=70):
        print("First")
elif(marks<35):
    pritn("fail")

Enter the marks 55
Pass
First


## Airthmetic operators

    Operation	Meaning
    
    +	addition
    
    -	subtraction
    
    *	multiplication
    
    /	true division
    
    //	integer division
    
    %	the modulo operator


In [3]:
48/4

12.0

In [4]:
48//4

12

In [6]:
##ignores the decimal
48//5

9

In [9]:
48%5


3

## python tutorial-05

## abs()
abs(x) will return the absolute value of a number x which we pass in argument. The number x can be integer, float, complex,..

In [10]:
#aboslute method
abs(10)

10

In [11]:
abs(-20)

20

In [12]:
abs(34.20)

34.2

In [13]:
abs(-55.02)

55.02

## ceil()
ceil(x) will return the ceiling value of a number x which we pass in argument. The ceiling value of a number x will be the smallest integer not less than x

Note :- This function will not be accessible directly using ceil() method. Math module will be required to access this method.

In [14]:
import math

In [16]:
math.ceil(43.67)

44

In [17]:
math.ceil(43.2)

44

In [19]:
math.ceil(43.05)

44

In [20]:
math.ceil(-44.05)

-44

## floor

In [21]:
math.floor(43.1)

43

In [22]:
math.floor(43.9)

43

In [24]:
math.floor(-43.8)

-44

## exp()
exp(x) will return the exponential value of a number x which we pass in argument.

**Note:- ** This function will not be accessible directly using exp() method. Math module will be required to access this method.

In [25]:
math.exp(10)

22026.465794806718

In [26]:
math.exp(-9)

0.00012340980408667956

## fabs()

In [27]:
math.fabs(10.5)

10.5

In [28]:
math.fabs(-10)

10.0

In [31]:
math.fabs(-0.314*2)

0.628

## log()

In [32]:
math.log(20)

2.995732273553991

In [34]:
math.log(12.45)

2.5217206229107165

In [37]:
#this is log to the base '10'
math.log10(10)

1.0

In [38]:
#this is log to the base 'e'
math.log(10)

2.302585092994046

## Max()

In [41]:
max(10,12,34,543,143,-322)

543

In [45]:
min(21,24,54,-3,35,-32)

-32

## power

In [46]:
math.pow(2,5)

32.0

In [47]:
math.pow(2,4)

16.0

In [48]:
math.pow(56,23)

1.6155656889615733e+40

In [49]:
math.pow(-5,-5)

-0.00032

## sqrt()

In [50]:
math.sqrt(16)

4.0

In [51]:
math.sqrt(256)

16.0

## Triginometry function

In [54]:
math.sin(0)

0.0

In [55]:
math.sin(45)

0.8509035245341184

In [56]:
math.cos(0)

1.0

In [57]:
math.tan(45)

1.6197751905438615

## hypotenius

In [60]:
math.hypot(3,4)

5.0

## Assignment
math.modf()

program to check the prime numbers

progam to check max of three numbers

In [6]:
import math
math.modf(4)
#Return the fractional and integer parts of x.

(0.0, 4.0)

In [10]:
#program to check the prime numbers
num=int(input("Enter the number"))
if(num%2 and num%3 != 0):
    print("the number is prime number")
elif(num==0):
    print("the number is zero")
else:
    print("the number is not prime number")

Enter the number45
the number is not prime number


## python tutorial- 06
## Lists
A list is a data structure in Python that is a mutable, or changeable, ordered sequence of elements. Each element or value that is inside of a list is called an item. Just as strings are defined as characters between quotes, lists are defined by having values between square brackets [ ]


In [5]:
#mutable vs immutable
str1="Atg"
print(str1)
type(str1)

Atg


str

In [6]:
str1="check"
print(str1)

check


In [8]:
type("")

str

In [10]:
str1[0]

'c'

In [12]:
# strings are immutable
str1[2] ="e"

TypeError: 'str' object does not support item assignment

In [24]:
# list []
lst=[1,2,3,4,"hi","nice"]
print(lst)
print(lst[4])
lst[4]="hello"
print(lst)
print(lst[4])

[1, 2, 3, 4, 'hi', 'nice']
hi
[1, 2, 3, 4, 'hello', 'nice']
hello


In [31]:
lst=list((1,2,3,4,5))
type(lst)
print(lst)

[1, 2, 3, 4, 5]


In [30]:
del list


In [32]:
lst

[1, 2, 3, 4, 5]

In [34]:
for i in lst:
    print(i**2)

1
4
9
16
25


In [35]:
max(lst)

5

In [36]:
min(lst)

1

## append
viewing inbuilt functions

In [38]:
#.append is used to add elements in the list
lst.append("atg")
lst


[1, 2, 3, 4, 5, 'atg']

In [42]:
lst.append([22,"shikamaru"])
lst

[1,
 2,
 3,
 4,
 5,
 'atg',
 [22, 'shikamaru'],
 [22, 'shikamaru'],
 [22, 'shikamaru'],
 [22, 'shikamaru']]

In [43]:
lst[6]

[22, 'shikamaru']

In [44]:
lst[7][1]

'shikamaru'

In [45]:
lst[2:]

[3,
 4,
 5,
 'atg',
 [22, 'shikamaru'],
 [22, 'shikamaru'],
 [22, 'shikamaru'],
 [22, 'shikamaru']]

In [47]:
lst[:7]

[1, 2, 3, 4, 5, 'atg', [22, 'shikamaru']]

## insert

In [48]:
## insert in a specific order
lst.insert(2,"taMg")

In [49]:
lst

[1,
 2,
 'taMg',
 3,
 4,
 5,
 'atg',
 [22, 'shikamaru'],
 [22, 'shikamaru'],
 [22, 'shikamaru'],
 [22, 'shikamaru']]

## Extend method

In [50]:
lst=[1,2,3,4,5,6]

In [51]:
lst.extend([8,9])

In [52]:
lst

[1, 2, 3, 4, 5, 6, 8, 9]

## Various Operation that we can perform in list

In [53]:
lst=[1,2,3,4,5,6]

In [54]:
sum(lst)

21

In [55]:
# it gets appended by 5
lst*5

[1,
 2,
 3,
 4,
 5,
 6,
 1,
 2,
 3,
 4,
 5,
 6,
 1,
 2,
 3,
 4,
 5,
 6,
 1,
 2,
 3,
 4,
 5,
 6,
 1,
 2,
 3,
 4,
 5,
 6]

In [56]:
lst/5

TypeError: unsupported operand type(s) for /: 'list' and 'int'

In [58]:
for i in lst:
    print(i/5)

0.2
0.4
0.6
0.8
1.0
1.2


## pop() Method

In [59]:
lst.pop()

6

In [60]:
lst

[1, 2, 3, 4, 5]

In [61]:
lst.pop(2)

3

In [62]:
lst

[1, 2, 4, 5]

## count():Calculates total occurrence of given element of List

In [63]:
lst=[1,1,2,3,4,5]
lst.count(1)

2

In [64]:
#length:Calculates total length of List
len(lst)

6

In [65]:
# index(): Returns the index of first occurrence. Start and End index are not necessary parameters
lst.index(1,1,4)

1

## python Tutorial - 07
## SETS
A Set is an unordered collection data type that is iterable, mutable, and has no duplicate elements. Python's set class represents the mathematical notion of a set.This is based on a data structure known as a hash table

In [5]:
type({1})

print(set([1,2,3,4,5,6,4]))

{1, 2, 3, 4, 5, 6}


In [6]:
## Defining an empty set

set_var= set()
print(set_var)
print(type(set_var))

set()
<class 'set'>


In [7]:
set_var= {1,2,3,4,5,3,1,2}

In [8]:
set_var

{1, 2, 3, 4, 5}

In [9]:
set_var={"Avengers","IronMan",'Hitman'}
print(set_var)
type(set_var)

{'Avengers', 'Hitman', 'IronMan'}


set

In [ ]:
# set is not susceptable

In [10]:
for i in set_var:
    print(i)

Avengers
Hitman
IronMan


In [11]:
# inbuilt function in sets

set_var.add("Hulk")

In [12]:
set_var

{'Avengers', 'Hitman', 'Hulk', 'IronMan'}

In [13]:
set_1=set([1,4,2,5,7,4,3])
print(set_1)

{1, 2, 3, 4, 5, 7}


In [15]:
set_1.add(6)
print(set_1)

{1, 2, 3, 4, 5, 6, 7}


In [32]:
set1={"Avengers","IronMan",'Hitman'}
set2={"Avengers","IronMan",'Hitman','Hulk2'}

In [33]:
set2.intersection(set1)

{'Avengers', 'Hitman', 'IronMan'}

In [34]:
set2

{'Avengers', 'Hitman', 'Hulk2', 'IronMan'}

In [35]:
set2

{'Avengers', 'Hitman', 'Hulk2', 'IronMan'}

In [36]:
## Difference update

set2.difference(set1)

{'Hulk2'}

In [37]:
print(set2)


{'Avengers', 'Hulk2', 'Hitman', 'IronMan'}


In [38]:
set2.intersection_update(set1)

In [39]:
set2

{'Avengers', 'Hitman', 'IronMan'}

In [40]:
set2.difference(set1)

set()

In [41]:
set2.issuperset(set1)

True

In [43]:
set2.isdisjoint(set1)

False

## Dictionaries
A dictionary is a collection which is unordered, changeable and indexed. In Python dictionaries are written with curly brackets, and they have keys and values.

In [47]:
type({1:"atg"})

dict

In [48]:
print((dict(name="atg",age=21)))

{'name': 'atg', 'age': 21}


In [46]:
dic={}
type(dic)

dict

In [49]:
set_ex={1,2,3,4,5}

In [50]:
type(set_ex)

set

In [51]:
## Let create a dictionary

my_dict={"Car1": "Audi", "Car2":"BMW","Car3":"Mercidies Benz"}

In [52]:
type(my_dict)

dict

In [54]:
my_dict["Car1"]

'Audi'

In [55]:
my_dict.items()

dict_items([('Car1', 'Audi'), ('Car2', 'BMW'), ('Car3', 'Mercidies Benz')])

In [56]:
my_dict.keys()

dict_keys(['Car1', 'Car2', 'Car3'])

In [57]:
my_dict.values()

dict_values(['Audi', 'BMW', 'Mercidies Benz'])

In [58]:
# We can even loop throught the dictionaries keys

for x in my_dict:
    print(x)

Car1
Car2
Car3


In [59]:
for x in my_dict.values():
    print(x)

Audi
BMW
Mercidies Benz


In [60]:
for x in my_dict.items():
    print(x)

('Car1', 'Audi')
('Car2', 'BMW')
('Car3', 'Mercidies Benz')


In [62]:
my_dict["car$"]="Ambassodar"

In [64]:
my_dict

{'Car1': 'Audi', 'Car2': 'BMW', 'Car3': 'Mercidies Benz', 'car$': 'Ambassodar'}

## Nested Dictionary

In [65]:
car1_model={'Mercedes':1960}
car2_model={'Audi':1970}
car3_model={'Ambassador':1980}

car_type={'car1':car1_model,'car2':car2_model,'car3':car3_model}

In [66]:
print(car_type)

{'car1': {'Mercedes': 1960}, 'car2': {'Audi': 1970}, 'car3': {'Ambassador': 1980}}


In [69]:
car_type['car2']['Audi']

1970

## Tuples

In [71]:
my_tuple=tuple()

In [73]:
type(my_tuple)

tuple

In [75]:
my_tuple.count(1)

0

In [85]:
my_tuple=("atg","jack","shelby","jack")

In [86]:
my_tuple.count('jack')

2

In [82]:
print(type(my_tuple))
print(my_tuple)

<class 'tuple'>
('atg', 'jack', 'shelby')


In [87]:
## Inbuilt function
my_tuple.count('atg')

1

In [88]:
my_tuple[2]

'shelby'

In [91]:
my_tuple.index("jack")

1

In [92]:
my_tuple.index("shelby")

2

In [93]:
list(my_tuple)

['atg', 'jack', 'shelby', 'jack']

## Python Tutorial- 08

## Numpy Tutorials
NumPy is a general-purpose array-processing package. It provides a high-performance multidimensional array object, and tools for working with these arrays. It is the fundamental package for scientific computing with Python

## What is an array
An array is a data structure that stores values of same data type. In Python, this is the main difference between arrays and lists. While python lists can contain values corresponding to different data types, arrays in python can only contain values corresponding to same data type

In [1]:
## import the library
import numpy as np

In [7]:
lst=[1,2,3,4,5]
arr=np.array(lst)
arr

array([1, 2, 3, 4, 5])

In [8]:
type(arr)

numpy.ndarray

In [9]:
arr.shape

(5,)

In [12]:
# 2 dimentional array
lst1=[1,2,3,4,5]
lst2=[2,3,4,5,6]
lst3=[3,4,5,6,7]
arr1=np.array([lst1,lst2,lst3])

In [13]:
arr1

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])

In [14]:
arr1.shape

(3, 5)

In [15]:
arr

array([1, 2, 3, 4, 5])

In [16]:
# indexing in array
arr[3]

4

In [17]:
arr[1:]

array([2, 3, 4, 5])

In [18]:
arr[1:3]

array([2, 3])

In [19]:
arr[-1]

5

In [20]:
arr[:-1]

array([1, 2, 3, 4])

In [21]:
arr[::-1]

array([5, 4, 3, 2, 1])

In [24]:
arr[::-2]

array([5, 3, 1])

In [25]:
arr1

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])

In [32]:
arr1[:,3:]

array([[4, 5],
       [5, 6],
       [6, 7]])

In [34]:
arr1[:,1]

array([2, 3, 4])

In [29]:
arr1[1:3,1:3]

array([[3, 4],
       [4, 5]])

In [31]:
arr1[1:,3:]

array([[5, 6],
       [6, 7]])

In [41]:
#Assignment
arr1[:,::4]

array([[1, 5],
       [2, 6],
       [3, 7]])

In [42]:
##EDA
arr

array([1, 2, 3, 4, 5])

In [45]:
arr<2

array([ True, False, False, False, False])

In [44]:
arr[arr<2]

array([1])

In [46]:
arr1.shape

(3, 5)

In [47]:
arr1

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])

In [48]:
arr1.reshape(5,3)

array([[1, 2, 3],
       [4, 5, 2],
       [3, 4, 5],
       [6, 3, 4],
       [5, 6, 7]])

In [50]:
## mechanism to create an array
np.arange(1,10,1)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [51]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [52]:
np.arange(1,20,3)

array([ 1,  4,  7, 10, 13, 16, 19])

In [54]:
np.arange(1,10,1).reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [57]:
np.arange(1,20,2).reshape(2,5)

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19]])

In [58]:
np.arange(1,20,2).reshape(1,10,1)

array([[[ 1],
        [ 3],
        [ 5],
        [ 7],
        [ 9],
        [11],
        [13],
        [15],
        [17],
        [19]]])

In [59]:
np.arange(1,20,2).reshape(2,5,1)

array([[[ 1],
        [ 3],
        [ 5],
        [ 7],
        [ 9]],

       [[11],
        [13],
        [15],
        [17],
        [19]]])

In [60]:
arr

array([1, 2, 3, 4, 5])

In [61]:
arr*arr

array([ 1,  4,  9, 16, 25])

In [62]:
arr1*2

array([[ 2,  4,  6,  8, 10],
       [ 4,  6,  8, 10, 12],
       [ 6,  8, 10, 12, 14]])

In [65]:
np.ones((5,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [67]:
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [73]:
#randint helps to initialize random number
np.random.randint(10,50,4).reshape(2,2)

array([[15, 41],
       [11, 41]])

In [74]:
np.random.randn(5,6)

array([[ 0.01110955,  0.37153934, -1.21623092, -1.02403801,  1.48186616,
         1.08673285],
       [ 0.07642664, -0.85336698, -1.88926182, -1.04042363, -0.54582733,
         0.89291739],
       [ 0.08975894,  0.73314511,  1.26956181,  0.74009689,  1.28006071,
        -1.69590694],
       [ 0.89118675, -0.72005373, -0.67032069, -0.15701006, -0.051023  ,
        -0.86982501],
       [ 0.91246149, -1.51639742, -0.18634908, -0.67429381, -0.54517189,
         1.24962462]])

In [76]:
np.random.random_sample((4,6))

array([[0.38676907, 0.21178134, 0.10563689, 0.31986802, 0.90805252,
        0.46144533],
       [0.39274491, 0.73811652, 0.02484623, 0.76564439, 0.75891556,
        0.9087368 ],
       [0.89831045, 0.04432539, 0.70138866, 0.96637633, 0.58573751,
        0.75714423],
       [0.73569418, 0.20790968, 0.20664181, 0.50072412, 0.12169006,
        0.13636545]])

## Tutorial 9- Python Pandas Tutorials- Part 1
In Part we are going to learn about

1.Pandas Dataframe

2.Pandas Series

3.Pandas Basic Operations

In [1]:
!pip install pandas

In [2]:
import pandas as pd
import numpy as np

In [3]:
np.arange(0,20).reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [4]:
## Create Dataframe
df=pd.DataFrame(data=np.arange(0,20).reshape(5,4),index=["Row1",
                                                      "Row2","Row3",
                                                      "Row4","Row5"],columns=["Column1",
                                                                             "Column2",
                                                                             "Column3",
                                                                             "Column4"])

In [5]:
df.head()

Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19

In [6]:
df.tail()

Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19

In [8]:
print(pd.__version__)

2.0.3


In [12]:
type(df)

pandas.core.frame.DataFrame

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, Row1 to Row5
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Column1  5 non-null      int32
 1   Column2  5 non-null      int32
 2   Column3  5 non-null      int32
 3   Column4  5 non-null      int32
dtypes: int32(4)
memory usage: 120.0+ bytes


In [15]:
df.describe()

Column1    Column2    Column3    Column4
count   5.000000   5.000000   5.000000   5.000000
mean    8.000000   9.000000  10.000000  11.000000
std     6.324555   6.324555   6.324555   6.324555
min     0.000000   1.000000   2.000000   3.000000
25%     4.000000   5.000000   6.000000   7.000000
50%     8.000000   9.000000  10.000000  11.000000
75%    12.000000  13.000000  14.000000  15.000000
max    16.000000  17.000000  18.000000  19.000000

In [16]:
##Indexing 
# columnname, rowindex[loc], rowindex columindex number[.iloc]
df.head()

Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19

In [31]:
#columnname
df['Column1']

Row1     0
Row2     4
Row3     8
Row4    12
Row5    16
Name: Column1, dtype: int32

In [32]:
df[['Column1','Column2','Column3']]

Column1  Column2  Column3
Row1        0        1        2
Row2        4        5        6
Row3        8        9       10
Row4       12       13       14
Row5       16       17       18

In [33]:
type(df['Column1'])

pandas.core.series.Series

In [34]:
type(df[['Column1','Column2','Column3']])

pandas.core.frame.DataFrame

In [35]:
# series vs dataframe
#df- if multiple rows and colums are taken
#series- if single row or single column is taken

In [36]:
#by using row index name loc
df.loc[['Row3','Row4']]

Column1  Column2  Column3  Column4
Row3        8        9       10       11
Row4       12       13       14       15

In [37]:
type(df.loc['Row3'])

pandas.core.series.Series

In [38]:
# rowindex columindex number[.iloc]
df.iloc[2:4,0:2]

Column1  Column2
Row3        8        9
Row4       12       13

In [40]:
df.iloc[2:4,1:]

Column2  Column3  Column4
Row3        9       10       11
Row4       13       14       15

In [43]:
df.iloc[:,::3]

Column1  Column4
Row1        0        3
Row2        4        7
Row3        8       11
Row4       12       15
Row5       16       19

In [45]:
df.iloc[:,1:]

Column2  Column3  Column4
Row1        1        2        3
Row2        5        6        7
Row3        9       10       11
Row4       13       14       15
Row5       17       18       19

In [46]:
#convert dataframe into arrays
df.iloc[:,1:].values

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11],
       [13, 14, 15],
       [17, 18, 19]])

In [47]:
#Basic operations
df.isnull().sum()

Column1    0
Column2    0
Column3    0
Column4    0
dtype: int64

In [54]:
cf=pd.DataFrame(data=[[1,"BMW",3],[2,"Volvo",7],[3,"Ford",np.nan]],index=["row0","row1","row2"],columns=["S.N","Cars",
                                                                             "Passings"])

In [55]:
cf.head()

S.N   Cars  Passings
row0    1    BMW       3.0
row1    2  Volvo       7.0
row2    3   Ford       NaN

In [57]:
cf.isnull().sum()

S.N         0
Cars        0
Passings    1
dtype: int64

In [59]:
cf.isnull()

S.N   Cars  Passings
row0  False  False     False
row1  False  False     False
row2  False  False      True

In [63]:
cf['Cars'].value_counts()

Cars
BMW      1
Volvo    1
Ford     1
Name: count, dtype: int64

In [64]:
df

Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19

In [66]:
df['Column2'].unique()

array([ 1,  5,  9, 13, 17])

In [69]:
df[df['Column2']>2]

Column1  Column2  Column3  Column4
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19